pipeline {
  agent any
  
  stages {
    stage('Test') {
      steps {
        script {
          docker.image('node:16-alpine').inside {
            sh 'node --version'
          }
        }
      }
    }
  }
}
